Traceback (most recent call last):
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/bose/base_task.py", line 117, in run_task
    self.run(driver)
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 269, in run
    result = get_data(self.scroll_times)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 248, in get_data
    links = get_links(q, sc_time)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 131, in get_links
    scroll_till_end(sc_time)
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 109, in scroll_till_end
    visit_gmap()
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 90, in visit_gmap
    if not driver.is_in_page(endpoint, Wait.LONG * 3):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/bose/boss_driver.py", line 257, in is_in_page
    if check_page(self, target):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/bose/boss_driver.py", line 245, in check_page
    return target in driver.current_url
                     ^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 530, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=113.0.5672.126)
Stacktrace:
#0 0x561facb39b73 <unknown>
#1 0x561fac882416 <unknown>
#2 0x561fac85c5fc <unknown>
#3 0x561fac8e357f <unknown>
#4 0x561fac8f6596 <unknown>
#5 0x561fac8de403 <unknown>
#6 0x561fac8b2f0a <unknown>
#7 0x561fac8b3ffe <unknown>
#8 0x561facafac4e <unknown>
#9 0x561facafe8f2 <unknown>
#10 0x561facb07870 <unknown>
#11 0x561facaff933 <unknown>
#12 0x561facad375e <unknown>
#13 0x561facb21e48 <unknown>
#14 0x561facb21fd7 <unknown>
#15 0x561facb31e39 <unknown>
#16 0x7f2504494b43 <unknown>

